import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { inventoryApi, salesApi } from '../api/client'
import type { Almacen, Cliente, Producto } from '../api/client'
import { AppLayout } from '../components/AppLayout'

type Line = { product: Producto; cantidad: number; precioUnitario: number }
export function NuevaVentaPage() {
  const [clients, setClients] = useState<Cliente[]>([]), [warehouses, setWarehouses] = useState<Almacen[]>([]), [products, setProducts] = useState<Producto[]>([])
  const [clienteId, setClienteId] = useState(''), [almacenId, setAlmacenId] = useState(''), [productId, setProductId] = useState(''), [lines, setLines] = useState<Line[]>([]), [observacion, setObservacion] = useState(''), [message, setMessage] = useState('')
  useEffect(() => { Promise.all([salesApi.clientes(), inventoryApi.almacenes(), inventoryApi.productos()]).then(([c,w,p]) => { setClients(c); setWarehouses(w); setProducts(p) }).catch((e: Error) => setMessage(e.message)) }, [])
  const preview = useMemo(() => lines.reduce((sum, x) => { const total = Math.round(x.cantidad * x.precioUnitario * 100) / 100; const subtotal = x.product.afectoIgv ? Math.round(total / 1.18 * 100) / 100 : total; return { subtotal: sum.subtotal + subtotal, igv: sum.igv + total - subtotal, total: sum.total + total } }, { subtotal: 0, igv: 0, total: 0 }), [lines])
  function addProduct() { const product = products.find(x => x.id === productId); if (!product || lines.some(x => x.product.id === product.id)) return; setLines(x => [...x, { product, cantidad: 1, precioUnitario: product.precioVenta }]); setProductId('') }
  async function submit(e: FormEvent) { e.preventDefault(); try { const sale = await salesApi.createVenta({ clienteId: clienteId || undefined, almacenId, items: lines.map(x => ({ productoId: x.product.id, cantidad: x.cantidad, precioUnitario: x.precioUnitario })), observacion }); window.location.href = `/ventas/${sale.id}` } catch (error) { setMessage((error as Error).message) } }
  return <AppLayout title="Nueva venta"><form onSubmit={submit}><div className="grid-form"><select value={clienteId} onChange={e => setClienteId(e.target.value)}><option value="">Consumidor final</option>{clients.map(x => <option key={x.id} value={x.id}>{x.numeroDocumento} - {x.nombreRazonSocial}</option>)}</select><select value={almacenId} onChange={e => setAlmacenId(e.target.value)} required><option value="">Almacén</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.nombre}</option>)}</select><input placeholder="Observación" value={observacion} onChange={e => setObservacion(e.target.value)}/></div><div className="toolbar"><select value={productId} onChange={e => setProductId(e.target.value)}><option value="">Seleccionar producto</option>{products.map(x => <option key={x.id} value={x.id}>{x.codigo} - {x.nombre}</option>)}</select><button type="button" onClick={addProduct}>Agregar</button></div><table><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Total</th><th></th></tr></thead><tbody>{lines.map((line, index) => <tr key={line.product.id}><td>{line.product.nombre}</td><td><input type="number" min="0.0001" step="0.0001" value={line.cantidad} onChange={e => setLines(current => current.map((x,i) => i === index ? {...x, cantidad: Number(e.target.value)} : x))}/></td><td><input type="number" min="0" step="0.01" value={line.precioUnitario} onChange={e => setLines(current => current.map((x,i) => i === index ? {...x, precioUnitario: Number(e.target.value)} : x))}/></td><td>S/ {(line.cantidad * line.precioUnitario).toFixed(2)}</td><td><button type="button" onClick={() => setLines(x => x.filter((_,i) => i !== index))}>Quitar</button></td></tr>)}</tbody></table><div className="totals"><span>Subtotal: S/ {preview.subtotal.toFixed(2)}</span><span>IGV: S/ {preview.igv.toFixed(2)}</span><strong>Total: S/ {preview.total.toFixed(2)}</strong></div>{message && <p className="message">{message}</p>}<button className="submit-sale" disabled={!almacenId || lines.length === 0}>Registrar venta</button></form></AppLayout>
}
